apiVersion: v1
kind: Secret
metadata:
  name: openobserve-credentials
  namespace: observability
type: Opaque
stringData:
  ZO_ROOT_USER_EMAIL: "naitikagarwal031@gmail.com"
  ZO_ROOT_USER_PASSWORD: "Naitik123@"

  OPENOBSERVE_USER: "naitikagarwal031@gmail.com"
  OPENOBSERVE_PASSWORD: "Naitik123@"

  OPENOBSERVE_LOGS_URL: "http://openobserve.observability.svc.cluster.local:5080/api/default/dummy_logs/_json"

  
  OPENOBSERVE_METRICS_URL: "http://openobserve.observability.svc.cluster.local:5080/api/default/prometheus/api/v1/write"