apiVersion: v1
kind: Service
metadata:
  name: openobserve
  namespace: observability
  labels:
    app: openobserve
  annotations:
    
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    
spec:
  type: LoadBalancer
  selector:
    app: openobserve

  

  ports:
    
    - name: http
      port: 5080
      targetPort: 5080
      protocol: TCP

